// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CrearReservasConfirmadas21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrearReservasConfirmadas21));
        
        string IMigrationMetadata.Id
        {
            get { return "201811101701126_CrearReservasConfirmadas21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
